# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# season 1
Episode.create(
  [
    {"episode": 1.1, "season": 1, "title": "Help Wanted"},
    {"episode": 1.2, "season": 1, "title": "Reef Blower"},
    {"episode": 1.3, "season": 1, "title": "Tea at the Treedome"},
    {"episode": 2.1, "season": 1, "title": "Bubblestand"},
    {"episode": 2.2, "season": 1, "title": "Ripped Pants"},
    {"episode": 3.1, "season": 1, "title": "Jellyfishing"},
    {"episode": 3.2, "season": 1, "title": "Plankton!"},
    {"episode": 4.1, "season": 1, "title": "Naughty Nautical Neighbors"},
    {"episode": 4.2, "season": 1, "title": "Boating School"},
    {"episode": 5.1, "season": 1, "title": "Pizza Delivery"},
    {"episode": 5.2, "season": 1, "title": "Home Sweet Pineapple"},
    {"episode": 6.1, "season": 1, "title": "Mermaid Man and Barnacle Boy"},
    {"episode": 6.2, "season": 1, "title": "Pickles"},
    {"episode": 7.1, "season": 1, "title": "Hall Monitor"},
    {"episode": 7.2, "season": 1, "title": "Jellyfish Jam"},
    {"episode": 8.1, "season": 1, "title": "Sandy's Rocket"},
    {"episode": 8.2, "season": 1, "title": "Squeaky Boots"},
    {"episode": 9.1, "season": 1, "title": "Nature Pants"},
    {"episode": 9.2, "season": 1, "title": "Opposite Day"},
    {"episode": 10.1, "season": 1, "title": "Culture Shock"},
    {"episode": 10.2, "season": 1, "title": "F.U.N."},
    {"episode": 11.1, "season": 1, "title": "MuscleBob BuffPants"},
    {"episode": 11.2, "season": 1, "title": "Squidward the Unfriendly Ghost"},
    {"episode": 12.1, "season": 1, "title": "The Chaperone"},
    {"episode": 12.2, "season": 1, "title": "Employee of the Month"},
    {"episode": 13.1, "season": 1, "title": "Scaredy Pants"},
    {"episode": 13.2, "season": 1, "title": "I Was a Teenage Gary"},
    {"episode": 14.1, "season": 1, "title": "SB-129"},
    {"episode": 14.2, "season": 1, "title": "Karate Choppers"},
    {"episode": 15.1, "season": 1, "title": "Sleepy Time"},
    {"episode": 15.2, "season": 1, "title": "Suds"},
    {"episode": 16.1, "season": 1, "title": "Valentine's Day"},
    {"episode": 16.2, "season": 1, "title": "The Paper"},
    {"episode": 17.1, "season": 1, "title": "Arrgh!"},
    {"episode": 17.2, "season": 1, "title": "Rock Bottom"},
    {"episode": 18.1, "season": 1, "title": "Texas"},
    {"episode": 18.2, "season": 1, "title": "Walking Small"},
    {"episode": 19.1, "season": 1, "title": "Fools in April"},
    {"episode": 19.2, "season": 1, "title": "Neptune's Spatula"},
    {"episode": 20.1, "season": 1, "title": "Hooky"},
    {"episode": 20.2, "season": 1, "title": "Mermaid Man and Barnacle Boy II"}
  ]
)

# season 2
Episode.create(
  [
    {"episode": 21.1, "season": 2, "title": "Your Shoe's Untied"},
    {"episode": 21.2, "season": 2, "title": "Squid's Day Off"},
    {"episode": 22.1, "season": 2, "title": "Something Smells"},
    {"episode": 22.2, "season": 2, "title": "Bossy Boots"},
    {"episode": 23.1, "season": 2, "title": "Big Pink Loser"},
    {"episode": 23.2, "season": 2, "title": "Bubble Buddy"},
    {"episode": 24.1, "season": 2, "title": "Dying for Pie"},
    {"episode": 24.2, "season": 2, "title": "Imitation Krabs"},
    {"episode": 25.1, "season": 2, "title": "Wormy"},
    {"episode": 25.2, "season": 2, "title": "Patty Hype"},
    {"episode": 26.1, "season": 2, "title": "Grandma's Kisses"},
    {"episode": 26.2, "season": 2, "title": "Squidville"},
    {"episode": 27.1, "season": 2, "title": "Prehibernation Week"},
    {"episode": 27.2, "season": 2, "title": "Life of Crime"},
    {"episode": 28.1, "season": 2, "title": "Christmas Who?"},
    {"episode": 29.1, "season": 2, "title": "Survival of the Idiots"},
    {"episode": 29.2, "season": 2, "title": "Dumped"},
    {"episode": 30.1, "season": 2, "title": "No Free Rides"},
    {"episode": 30.2, "season": 2, "title": "I'm Your Biggest Fanatic"},
    {"episode": 31.1, "season": 2, "title": "Mermaid Man and Barnacle Boy III"},
    {"episode": 31.2, "season": 2, "title": "Squirrel Jokes"},
    {"episode": 32.1, "season": 2, "title": "Pressure"},
    {"episode": 32.2, "season": 2, "title": "The Smoking Peanut"},
    {"episode": 33.1, "season": 2, "title": "Shanghaied"},
    {"episode": 33.2, "season": 2, "title": "Gary Takes a Bath"},
    {"episode": 34.1, "season": 2, "title": "Welcome to the Chum Bucket"},
    {"episode": 34.2, "season": 2, "title": "Frankendoodle"},
    {"episode": 35.1, "season": 2, "title": "The Secret Box"},
    {"episode": 35.2, "season": 2, "title": "Band Geeks"},
    {"episode": 36.1, "season": 2, "title": "Graveyard Shift"},
    {"episode": 36.2, "season": 2, "title": "Krusty Love"},
    {"episode": 37.1, "season": 2, "title": "Procrastination"},
    {"episode": 37.2, "season": 2, "title": "I'm with Stupid"},
    {"episode": 38.1, "season": 2, "title": "Sailor Mouth"},
    {"episode": 38.2, "season": 2, "title": "Artist Unknown"},
    {"episode": 39.1, "season": 2, "title": "Jellyfish Hunter"},
    {"episode": 39.2, "season": 2, "title": "The Fry Cook Games"},
    {"episode": 40.1, "season": 2, "title": "Squid on Strike"},
    {"episode": 40.2, "season": 2, "title": "Sandy, SpongeBob, and the Worm"}
  ]
)

# season 3
Episode.create(
  [
    {"episode": 41.1, "season": 3, "title": "The Algae's Always Greener"},
    {"episode": 41.2, "season": 3, "title": "SpongeGuard on Duty"},
    {"episode": 42.1, "season": 3, "title": "Club SpongeBob"},
    {"episode": 42.2, "season": 3, "title": "My Pretty Seahorse"},
    {"episode": 43.1, "season": 3, "title": "The Bully"},
    {"episode": 43.2, "season": 3, "title": "Just One Bite"},
    {"episode": 44.1, "season": 3, "title": "Nasty Patty"},
    {"episode": 44.2, "season": 3, "title": "Idiot Box"},
    {"episode": 45.1, "season": 3, "title": "Mermaid Man and Barnacle Boy IV"},
    {"episode": 45.2, "season": 3, "title": "Doing Time"},
    {"episode": 46.1, "season": 3, "title": "Snowball Effect"},
    {"episode": 46.2, "season": 3, "title": "One Krab's Trash"},
    {"episode": 47.1, "season": 3, "title": "As Seen on TV"},
    {"episode": 47.2, "season": 3, "title": "Can You Spare a Dime?"},
    {"episode": 48.1, "season": 3, "title": "No Weenies Allowed"},
    {"episode": 48.2, "season": 3, "title": "Squilliam Returns"},
    {"episode": 49.1, "season": 3, "title": "Krab Borg"},
    {"episode": 49.2, "season": 3, "title": "Rock-a-Bye Bivalve"},
    {"episode": 50.1, "season": 3, "title": "Wet Painters"},
    {"episode": 50.2, "season": 3, "title": "Krusty Krab Training Video"},
    {"episode": 51.1, "season": 3, "title": "Party Pooper Pants"},
    {"episode": 52.1, "season": 3, "title": "Chocolate with Nuts"},
    {"episode": 52.2, "season": 3, "title": "Mermaid Man and Barnacle Boy V"},
    {"episode": 53.1, "season": 3, "title": "New Student Starfish"},
    {"episode": 53.2, "season": 3, "title": "Clams"},
    {"episode": 54.1, "season": 3, "title": "Ugh"},
    {"episode": 55.1, "season": 3, "title": "The Great Snail Race"},
    {"episode": 55.2, "season": 3, "title": "Mid-Life Crustacean"},
    {"episode": 56.1, "season": 3, "title": "Born Again Krabs"},
    {"episode": 56.2, "season": 3, "title": "I Had an Accident"},
    {"episode": 57.1, "season": 3, "title": "Krabby Land"},
    {"episode": 57.2, "season": 3, "title": "The Camping Episode"},
    {"episode": 58.1, "season": 3, "title": "Missing Identity"},
    {"episode": 58.2, "season": 3, "title": "Plankton's Army"},
    {"episode": 59.1, "season": 3, "title": "The Sponge Who Could Fly"},
    {"episode": 60.1, "season": 3, "title": "SpongeBob Meets the Strangler"},
    {"episode": 60.2, "season": 3, "title": "Pranks a Lot"}
  ]
)

# season 4
Episode.create(
  [
    {"episode": 61.1, "season": 4, "title": "Fear of a Krabby Patty"},
    {"episode": 61.2, "season": 4, "title": "Shell of a Man"},
    {"episode": 62.1, "season": 4, "title": "The Lost Mattress"},
    {"episode": 62.2, "season": 4, "title": "Krabs vs. Plankton"},
    {"episode": 63.1, "season": 4, "title": "Have You Seen This Snail?"},
    {"episode": 64.1, "season": 4, "title": "Skill Crane"},
    {"episode": 64.2, "season": 4, "title": "Good Neighbors"},
    {"episode": 65.1, "season": 4, "title": "Selling Out"},
    {"episode": 65.2, "season": 4, "title": "Funny Pants"},
    {"episode": 66.1, "season": 4, "title": "Dunces and Dragons"},
    {"episode": 67.1, "season": 4, "title": "Enemy In-Law"},
    {"episode": 67.2, "season": 4, "title": "Mermaid Man and Barnacle Boy VI: The Motion Picture"},
    {"episode": 68.1, "season": 4, "title": "Patrick SmartPants"},
    {"episode": 68.2, "season": 4, "title": "SquidBob TentaclePants"},
    {"episode": 69.1, "season": 4, "title": "Krusty Towers"},
    {"episode": 69.2, "season": 4, "title": "Mrs. Puff, You're Fired"},
    {"episode": 70.1, "season": 4, "title": "Chimps Ahoy"},
    {"episode": 70.2, "season": 4, "title": "Ghost Host"},
    {"episode": 71.1, "season": 4, "title": "Whale of a Birthday"},
    {"episode": 71.2, "season": 4, "title": "Karate Island"},
    {"episode": 72.1, "season": 4, "title": "All That Glitters"},
    {"episode": 72.2, "season": 4, "title": "Wishing You Well"},
    {"episode": 73.1, "season": 4, "title": "New Leaf"},
    {"episode": 73.2, "season": 4, "title": "Once Bitten"},
    {"episode": 74.1, "season": 4, "title": "Bummer Vacation"},
    {"episode": 74.2, "season": 4, "title": "Wigstruck"},
    {"episode": 75.1, "season": 4, "title": "Squidtastic Voyage"},
    {"episode": 75.2, "season": 4, "title": "That's No Lady"},
    {"episode": 76.1, "season": 4, "title": "The Thing"},
    {"episode": 76.2, "season": 4, "title": "Hocus Pocus"},
    {"episode": 77.1, "season": 4, "title": "Driven to Tears"},
    {"episode": 77.2, "season": 4, "title": "Rule of Dumb"},
    {"episode": 78.1, "season": 4, "title": "Born to Be Wild"},
    {"episode": 78.2, "season": 4, "title": "Best Frenemies"},
    {"episode": 79.1, "season": 4, "title": "The Pink Purloiner"},
    {"episode": 79.2, "season": 4, "title": "Squid Wood"},
    {"episode": 80.1, "season": 4, "title": "Best Day Ever"},
    {"episode": 80.2, "season": 4, "title": "The Gift of Gum"}
  ]
)